import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import DashboardLayout from "@/components/layout/DashboardLayout";
import { SessionProvider } from "next-auth/react";


const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-geist-sans",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${nunito.variable} antialiased`}
      >
        
    <SessionProvider >
         <DashboardLayout>{children}</DashboardLayout>
    </SessionProvider>
      </body>
    </html>
  );
}
